#!/bin/sh
#
# /etc/init.d/ecs-sync-ui
# Subsystem file for "ecs-sync-ui" service.
#
# chkconfig: 3 75 10
# description: ECS-Sync-UI 2.1+ server deamon.
#
# processname: ecs-sync-ui
# config: 
export LANG=en_US.UTF-8
SERVICE_NAME=ecs-sync-ui

INSTALL_DIR=/opt/emc/ecs-sync
LOG_DIR=/var/log/ecs-sync

PATH_TO_JAR=$INSTALL_DIR/ecs-sync-ui.jar
PID_PATH_NAME=$LOG_DIR/ecs-sync-ui.pid
PATH_TO_LOG=$LOG_DIR/ecs-sync-ui.log
APP_USER=ecssync
JAVA_OPTS=-Xmx1G
# or, if you frequently run out of permgen space:
#JAVA_OPTS=-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled

start() {
    echo "Starting $SERVICE_NAME ..."
    if [ ! -f $PID_PATH_NAME ]; then
        su - $APP_USER <<EOF
cd $INSTALL_DIR
nohup java $JAVA_OPTS -jar $PATH_TO_JAR >> $PATH_TO_LOG 2>&1 &
echo \$! > $PID_PATH_NAME
EOF
        su - $APP_USER -c "nohup $LAUNCH_SCRIPT >> $PATH_TO_LOG 2>&1 & echo \$! > $PID_PATH_NAME"
        echo "$SERVICE_NAME started ..."
    else
        echo "$SERVICE_NAME is already running ..."
    fi
}

stop() {
    if [ -f $PID_PATH_NAME ]; then
        PID=$(cat $PID_PATH_NAME);
        echo "$SERVICE_NAME stoping ..."
        kill -9 $PID;
        echo "$SERVICE_NAME stopped ..."
        rm $PID_PATH_NAME
    else
        echo "$SERVICE_NAME is not running ..."
    fi
}

case $1 in
    start)
        start;
    ;;
    stop)
        stop;
    ;;
    restart)
        stop;
        start;
    ;;
esac
